ALTER TABLE stories ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE stories ADD COLUMN IF NOT EXISTS value TEXT;
ALTER TABLE stories ADD COLUMN IF NOT EXISTS module TEXT;
ALTER TABLE stories ADD COLUMN IF NOT EXISTS document_id UUID;
